### ISSUE TITLE
deprecated org--setup-collect-keywords

### ISSUE THREAD

**Issue by yiufung** [bastibe/org-journal#289]
https://github.com/bastibe/org-journal/blob/3ca0b26bd098ec1336f9f394367d2b647dbcd631/org-journal.el#L587

This has been replaced by `org-collect-keywords` since Org at commit `b4e91b7e9`. Would you consider to update it?

**Comment by cslux** [comment]
Thanks for the report. Should be fixed with commit 5ba7776.

**Comment by yiufung** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp 41)
  string-lessp(41 92)
  sort(("SETUPFILE" 94 91 32 9 93 42 35 92 43 92 40 92 40 63 58 70 73 76 69 84 65 71 83 92 124 83 69) string-lessp)
  regexp-opt(("SETUPFILE" 94 91 32 9 93 42 35 92 43 92 40 92 40 63 58 70 73 76 69 84 65 71 83 92 124 83 69 84 85 80 70 73 76 69 92 124 84 65 71 83 92 41 92 41 58 91 32 9 93 ...))
  (concat "^[ \11]*#\\+\\(" (regexp-opt kwds) (and extra (concat (and kwds "\\|") extra)) "\\):[ \11]*\\(.*\\)")
  org-make-options-regexp(("SETUPFILE" 94 91 32 9 93 42 35 92 43 92 40 92 40 63 58 70 73 76 69 84 65 71 83 92 124 83 69 84 85 80 70 73 76 69 92 124 84 65 71 83 92 41 92 41 58 91 32 9 93 ...))
  (let ((case-fold-search t) (regexp (org-make-options-regexp keywords))) (while (and keywords (re-search-forward regexp nil t)) (let ((element (org-element-at-point))) (if (eq 'keyword (org-element-type element)) (progn (let ((value ...)) (let* (...) (if ... ... ...))))))) alist)
  (save-restriction (widen) (goto-char (or --mpom (point))) (let ((case-fold-search t) (regexp (org-make-options-regexp keywords))) (while (and keywords (re-search-forward regexp nil t)) (let ((element (org-element-at-point))) (if (eq 'keyword (org-element-type element)) (progn (let (...) (let* ... ...)))))) alist))
  (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (let ((case-fold-search t) (regexp (org-make-options-regexp keywords))) (while (and keywords (re-search-forward regexp nil t)) (let ((element (org-element-at-point))) (if (eq 'keyword (org-element-type element)) (progn (let ... ...))))) alist)))
  (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (let ((case-fold-search t) (regexp (org-make-options-regexp keywords))) (while (and keywords (re-search-forward regexp nil t)) (let ((element ...)) (if (eq ... ...) (progn ...)))) alist))))
  (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (let ((case-fold-search t) (regexp (org-make-options-regexp keywords))) (while (and keywords (re-search-forward regexp nil t)) (let (...) (if ... ...))) alist)))))
  org--collect-keywords-1(("SETUPFILE" 94 91 32 9 93 42 35 92 43 92 40 92 40 63 58 70 73 76 69 84 65 71 83 92 124 83 69 84 85 80 70 73 76 69 92 124 84 65 71 83 92 41 92 41 58 91 32 9 93 ...) nil nil ("/home/yiufung/Dropbox/journals/journal/20200831.gp...") nil)
  (let* ((keywords (cons "SETUPFILE" (mapcar #'upcase keywords))) (unique (mapcar #'upcase unique)) (alist (org--collect-keywords-1 keywords unique directory (and buffer-file-name (list buffer-file-name)) nil))) (let ((--dolist-tail-- alist)) (while --dolist-tail-- (let ((entry (car --dolist-tail--))) (if (consp entry) (let* ((x200 ...)) (if (consp x200) (let ... ...) nil)) nil) (setq --dolist-tail-- (cdr --dolist-tail--))))) (nreverse alist))
  org--setup-collect-keywords("^[ \11]*#\\+\\(\\(?:FILETAGS\\|SETUPFILE\\|TAGS\\)\\):[ \11]*...")
  org-journal--set-current-tag-alist()
  org-journal-mode()
  set-auto-mode-0(org-journal-mode nil)
  #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1fcc3806e499>)()
  apply(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1fcc3806e499>) nil)
  (let ((so-long--set-auto-mode t)) (apply orig-fun args))
  so-long--set-auto-mode(#f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1fcc3806e499>))
  apply(so-long--set-auto-mode #f(compiled-function (&optional keep-mode-if-same) "Select major mode appropriate for current buffer.\n\nTo find the right major mode, this function checks for a -*- mode tag\nchecks for a `mode:' entry in the Local Variables section of the file,\nchecks if it uses an interpreter listed in `interpreter-mode-alist',\nmatches the buffer beginning against `magic-mode-alist',\ncompares the filename against the entries in `auto-mode-alist',\nthen matches the buffer beginning against `magic-fallback-mode-alist'.\n\nIf `enable-local-variables' is nil, or if the file name matches\n`inhibit-local-variables-regexps', this function does not check\nfor any mode: tag anywhere in the file.  If `local-enable-local-variables'\nis nil, then the only mode: tag that can be relevant is a -*- one.\n\nIf the optional argument KEEP-MODE-IF-SAME is non-nil, then we\nset the major mode only if that would change it.  In other words\nwe don't actually set it to the same mode the buffer already has." #<bytecode 0x1fcc3806e499>) nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer 20200831.gpg> "~/Dropbox/journals/journal/20200831.gpg" nil nil "~/Dropbox/journals/journal/20200831.gpg" (2895793 2049))
  find-file-noselect("/home/yiufung/Dropbox/journals/journal/20200831.gp..." nil nil nil)
  find-file-other-window("/home/yiufung/Dropbox/journals/journal/20200831.gp...")
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

I've updated to latest version, but still seeing this error message. Quite confusing

**Comment by cslux** [comment]
Ok. Can you provide a minimal example org-journal file to reproduce it as well as the output of `org-version`. Thanks!

**Comment by yiufung** [comment]
Please see the commit that introduce the change [here](https://code.orgmode.org/bzg/org-mode/commit/b4e91b7e944c900db6b8217d78011afcd2c1e62c?style=split). The two functions `org--setup-collect-keywords (regexp &optional files alist)` and `org-collect-keywords (keywords &optional uniques)` use different signatures, so I think it's not interchangeable. You can see how Nicolas uses the new function to replace the old [here](https://code.orgmode.org/bzg/org-mode/commit/b4e91b7e944c900db6b8217d78011afcd2c1e62c?style=split#diff-167462582fb5e0578aad18fdca90b20ee1ae776eL4240).

**Comment by cslux** [comment]
I completely overlooked that. Thanks, should be fixed now with https://github.com/bastibe/org-journal/commit/b4b9cbe18c89695ce832b607a1fd1577661d1460.
