### ISSUE TITLE
Org Journal new entry does not enter time prefix along with current time for daily files

### ISSUE THREAD

**Issue by aadi123** [bastibe/org-journal#411]
**Describe the bug**
Org Journal new entry does not enter time prefix along with current time for daily files. Only the date prefix and the date format.

**To Reproduce**
fresh doom emacs install.
enable journal integration

**Expected behavior**
Should see the current date along with the secondary heading and the time.
Ex:
```
* 08/06/2023
** 13:40
```

Instead I am only seeing
```
* 08/06/2023
```
On a new entry.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Emacs Version 28.2

**Your Emacs Configuration**
The part relevant to org-journal.
```
(after! org-journal
  (setq org-journal-enable-agenda-integration t)
  (setq org-journal-date-prefix "* ")
  (setq org-journal-date-format "Daily Log")
  (setq org-journal-file-header "#+title: %A, %x\n\n")
  (setq org-journal-time-prefix "** ")
  (setq org-journal-file-format "%Y-%m-%d.org")
  (setq org-journal-time-format "%I:%M %p"))
```

**Comment by ivanecr** [comment]
Same problem here.

 Every time I called "org-journal-new-entry" get a message  `created property timestamp format %y%m%d doesn't match CREATED protery value (nil) from entry at line: line 1`
 
 without displaying the current date `** 13:40`

**To Reproduce**
Emacs Version 28.2
doom emacs
arch linux
**Your Emacs Configuration**

(after! org-journal
  (setq org-journal-enable-agenda-integration t)
  (setq org-journal-date-prefix "* ")
  (setq org-journal-file-header 'org-journal-file-header-func)
  (setq org-journal-date-format "%A, %d %B %Y")
 (setq org-journal-file-format "%Y-W%V.org")
  (setq org-journal-time-prefix "** ")
  (setq org-journal-file-format "%Y-%m-%d.org")
  (setq org-journal-time-format "%I:%M %p"))

**Comment by g6ai** [comment]
I have recently upgraded Doom Emacs as well. Could it be related to Doom Emacs?

**Comment by linguistgate** [comment]
Not sure if relevant, but I have `org-journal-file-type` set to `'monthly` and I get the error "Created property timestamp format "%Y%m%d" doesn't matched CREATED property value (nil) from entry at line: Line 1" with just a date heading (*), not a time heading (**) being inserted. When setting `org-journal-file-type` to `'daily`, the error disappears and I get the second-level heading for time.

GNU Emacs     v28.2            nil
Doom core     v3.0.0-pre       HEAD -> master a44e8d6bf 2023-09-11 23:56:21 +0200
Doom modules  v23.09.0-pre     HEAD -> master a44e8d6bf 2023-09-11 23:56:21 +0200

**Comment by g6ai** [comment]
I reset the `org-journal-file-header` to empty string (by not setting it at all), and the issue is fixed. I have tried changing `org-journal-file-type` to different values, at first it fixes the issue, then it re-emerges (can't say when it re-emerges though). I suspect this is related to #416?

**Comment by linguistgate** [comment]
Not setting `org-jounral-file-type` doesn't seem to fix the error for me, unfortunately. Same error pops up, even after a full re-sync and Doom and restart of Emacs after changing the value to empty string/unsetting. Agree that this seems related to [#416](https://github.com/bastibe/org-journal/issues/416).

**Comment by Celibistrial** [comment]
any updates on how to fix this, have the same issue on my end...
using doom emacs and only have (setq org-journal-enable-encryption t) in my config
