### ISSUE TITLE
Error when org-journal-time-prefix is empty

### ISSUE THREAD

**Issue by geoffmacintosh** [bastibe/org-journal#65]
When my config contains the setting:

``` emacs-lisp
(setq org-journal-time-prefix "")
```

I get the error:

``` emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  hide-sublevels(nil)
  org-journal-new-entry(nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

This occurs with `emacs -Q` and my normal config. This seems like a bug, but I might be missing something. This is with Emacs 24.5.1 on El Capitan and org-journal 20160427.618 on Melpa.

**Comment by bastibe** [comment]
Hi Goeff, thank you for the bug report.

Your problem should be fixed in the latest release. The fix is already uploaded on Marmalade, and should show up on Melpa and Melpa Stable, soon.

**Comment by geoffmacintosh** [comment]
Hey!

I'd like to preface this by saying that I have no idea what I'm talking about, so forgive any huge mistakes.

I think your fix doesn't quite work for me, however using `when` instead of `if` does.

```emacs-lisp
(when (and org-journal-hide-entries-p (org-journal-time-entry-level))
```

This seems to work okay for me. Testing the structure in `M-x ielm` shows the following
```emacs-lisp
ELISP> (if (and t nil))
*** Eval error *** Wrong number of arguments: if, 1
ELISP> (when (and t nil))
nil
```

So I think using `when` provides the behaviour wanted? It seems to not have additional problems anyway. Searching through elisp guides hasn't uncovered anything anyway. I'm happy to submit a pull request, although my proposed change is one word. Thanks again!

**Comment by geoffmacintosh** [comment]
Immediate update: That doesn't fix everything. There's another section that goes
```emacs-lisp
(when should-add-entry-p
        (unless (eq (current-column) 0) (insert "\n"))
        (insert "\n" org-journal-time-prefix
                (if (= (time-to-days (current-time)) (time-to-days time))
                    (format-time-string org-journal-time-format)
                  "")))
```
That seems to get mad when attempting to insert org-journal-time-prefix because it's nil. I can investigate more.

**Comment by bastibe** [comment]
Thank you for the analysis. There should be no difference between `if` with two arguments and `when` with two arguments. The difference between the two is how the n>2 arguments are handled. `if` uses `(if predicate true-clause false-clause)`, whereas `when` uses `(when predicate true-clauses...)` with an arbitrary number of `true-clauses`.

As for the second section that causes you problems, why is your `org-journal-time-prefix` nil?. It should be empty-string, not nil. The rest of the code should work fine with an empty string.

**Comment by geoffmacintosh** [comment]
My apologies. I got a bit carried away and stopped testing things with `emacs -Q`. I now am in the situation where having these two items in my normal config:
```emacs-lisp
(setq org-journal-date-prefix "#+TITLE: Entry for ")
(setq org-journal-time-prefix "")
```
Causes the following error when I try to make a new entry or add to an existing entry:
```emacs-lisp
Debugger entered--Lisp error: (error "before first heading")
  signal(error ("before first heading"))
  error("before first heading")
  outline-back-to-heading(t)
  show-entry()
  org-journal-new-entry(nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```
But it doesn't happen using `emacs -Q`. This means it's pretty clearly my fault/config, which I think marks this issue as closed. Thanks for the bug fix and all of my additional nonsense!

**Comment by bastibe** [comment]
Yes, the last step of creating a new entry is to call `(show-entry)`, which reveals the current headline. Of course in your case, there is no headline, so `(show-entry)` fails. 

You can work around this by calling `(org-journal-new-entry)` with a prefix, which will suppress this, i.e. use C-u C-c C-j instead of C-c C-j.

A more permanent workaround would be to put this code into your init file:

```elisp
(defadvice org-journal-new-entry (around org-journal-new-entry-no-show-entry (prefix &optional time) activate)
  "suppress calls to show-entry within org-journal-new-entry"
  (interactive "P")
  (let ((show-entry (lambda nil))) ad-do-it))
```

This will override `show-entry` within `org-journal-new-entry` to do nothing (I haven't tested this, so there might still be syntax errors).
